// Local gender detection database - no external API needed
// Contains common first names mapped to gender

const MALE_NAMES = new Set([
    'aaron', 'abel', 'abraham', 'adam', 'adrian', 'aidan', 'aiden', 'alan', 'albert', 'alec', 'alejandro',
    'alex', 'alexander', 'alfred', 'ali', 'allen', 'alvin', 'amir', 'amos', 'andre', 'andrew', 'andy',
    'angel', 'anthony', 'antonio', 'archer', 'archie', 'ari', 'ariel', 'armando', 'arnold', 'arthur',
    'ashton', 'austin', 'avery', 'axel',
    'bailey', 'barack', 'barry', 'basil', 'beau', 'ben', 'benjamin', 'bennett', 'bernard', 'bill',
    'billy', 'blaine', 'blake', 'bob', 'bobby', 'boris', 'brad', 'braden', 'bradley', 'brady',
    'brandon', 'braxton', 'brendan', 'brennan', 'brent', 'brett', 'brian', 'briar', 'brock', 'brody',
    'bruce', 'bruno', 'bryan', 'bryce', 'byron',
    'caleb', 'calvin', 'cameron', 'carl', 'carlos', 'carter', 'casey', 'cecil', 'cedric', 'chad',
    'chance', 'chandler', 'charles', 'charlie', 'chase', 'chester', 'chris', 'christian', 'christopher',
    'clark', 'claude', 'clayton', 'clifford', 'clint', 'clyde', 'cody', 'colby', 'cole', 'colin',
    'colton', 'connor', 'conrad', 'cooper', 'corey', 'cornelius', 'craig', 'cristian', 'cruz', 'curtis', 'cyrus',
    'dale', 'dallas', 'dalton', 'damian', 'damon', 'dan', 'dane', 'daniel', 'danny', 'dante', 'darius',
    'darren', 'daryl', 'dave', 'david', 'davis', 'dawson', 'dean', 'declan', 'dennis', 'derek',
    'desmond', 'devin', 'devon', 'diego', 'dillon', 'dimitri', 'dirk', 'dominic', 'donald', 'donovan',
    'dorian', 'doug', 'douglas', 'drake', 'drew', 'duncan', 'dustin', 'dwight', 'dylan',
    'earl', 'easton', 'ed', 'eddie', 'edgar', 'edmond', 'edmund', 'eduardo', 'edward', 'edwin', 'eli',
    'elias', 'elijah', 'elliot', 'elliott', 'ellis', 'elmer', 'emerson', 'emil', 'emilio', 'emmanuel',
    'emmett', 'enrique', 'ephraim', 'erasmus', 'erhard', 'eric', 'erik', 'ernest', 'ernie', 'ervin',
    'ethan', 'eugene', 'evan', 'everett', 'ezekiel', 'ezra',
    'fabian', 'felix', 'felipe', 'fernando', 'finn', 'finnegan', 'fletcher', 'floyd', 'ford', 'forrest',
    'foster', 'francis', 'francisco', 'frank', 'franklin', 'fred', 'freddie', 'frederick', 'fritz',
    'gabriel', 'gage', 'gareth', 'garrett', 'garrison', 'gary', 'gavin', 'gene', 'geoffrey', 'george',
    'gerald', 'geraldo', 'gerard', 'gideon', 'gilbert', 'glen', 'glenn', 'gordon', 'grady', 'graham',
    'grant', 'greg', 'gregory', 'griffin', 'grover', 'guillermo', 'gunnar', 'gunner', 'gus', 'gustavo', 'guy',
    'hal', 'hank', 'hans', 'harlan', 'harold', 'harrison', 'harry', 'harvey', 'hasan', 'hassan', 'hayden',
    'heath', 'hector', 'henry', 'herbert', 'herman', 'holden', 'homer', 'howard', 'hubert', 'hudson',
    'hugh', 'hugo', 'hunter',
    'ian', 'ibrahim', 'ignacio', 'iker', 'irvin', 'irving', 'isaac', 'isaiah', 'ismael', 'israel', 'ivan',
    'jack', 'jackson', 'jacob', 'jacques', 'jaden', 'jake', 'jalen', 'james', 'jamie', 'jared', 'jarvis',
    'jason', 'jasper', 'javier', 'jay', 'jayden', 'jaylen', 'jeff', 'jeffery', 'jeffrey', 'jeremiah',
    'jeremy', 'jermaine', 'jerome', 'jerry', 'jesse', 'jesus', 'jim', 'jimmy', 'joaquin', 'jodi',
    'joe', 'joel', 'joey', 'johan', 'johann', 'john', 'johnathan', 'johnny', 'jon', 'jonah', 'jonathan',
    'jordan', 'jorge', 'jose', 'joseph', 'josh', 'joshua', 'josiah', 'jovan', 'juan', 'judah', 'jude',
    'julian', 'julio', 'julius', 'junior', 'justin',
    'kai', 'kaleb', 'kane', 'karl', 'keanu', 'keegan', 'keith', 'kelly', 'kelvin', 'kendrick', 'kenneth',
    'kenny', 'kent', 'kevin', 'kieran', 'killian', 'kingsley', 'kirk', 'knox', 'kobe', 'kolby', 'kurt', 'kyle',
    'lance', 'landon', 'larry', 'lars', 'lawrence', 'layne', 'lee', 'leo', 'leon', 'leonard', 'leonardo',
    'leroy', 'lester', 'levi', 'lewis', 'liam', 'lincoln', 'linus', 'lionel', 'lloyd', 'logan', 'lorenzo',
    'louie', 'louis', 'luca', 'lucas', 'lucian', 'luis', 'luke', 'luther',
    'mac', 'mack', 'malcolm', 'malik', 'manuel', 'marc', 'marco', 'marcos', 'marcus', 'mario', 'mark',
    'marlon', 'marquis', 'marshall', 'martin', 'marvin', 'mason', 'mathew', 'matias', 'matt', 'matthew',
    'matthias', 'maurice', 'maverick', 'max', 'maximilian', 'maxwell', 'michael', 'miguel', 'mike',
    'miles', 'milo', 'mitchell', 'mohammad', 'mohammed', 'morgan', 'morris', 'moses', 'muhammad', 'murphy',
    'nash', 'nathan', 'nathaniel', 'neal', 'neil', 'nelson', 'nicholas', 'nick', 'nicolas', 'nigel',
    'nikolai', 'noah', 'noel', 'nolan', 'norman',
    'oliver', 'omar', 'orlando', 'oscar', 'otis', 'otto', 'owen',
    'pablo', 'parker', 'patrick', 'paul', 'pedro', 'percy', 'perry', 'peter', 'peyton', 'phil',
    'philip', 'phillip', 'pierce', 'porter', 'preston', 'prince',
    'quentin', 'quincy', 'quinn',
    'rafael', 'ralph', 'ramiro', 'ramon', 'randall', 'randy', 'raul', 'ray', 'raymond', 'reed',
    'reese', 'reid', 'rene', 'rex', 'rhett', 'ricardo', 'richard', 'rick', 'ricky', 'riley', 'river',
    'rob', 'robert', 'roberto', 'robin', 'rocco', 'roderick', 'rodney', 'rodrigo', 'roger', 'roland',
    'roman', 'romeo', 'ron', 'ronald', 'ronan', 'rory', 'ross', 'roy', 'ruben', 'rudolph', 'rudy',
    'russell', 'ryan', 'ryder',
    'salvador', 'salvatore', 'sam', 'sammy', 'samuel', 'sanford', 'santiago', 'saul', 'sawyer', 'scott',
    'sean', 'sebastian', 'sergio', 'seth', 'shane', 'shaun', 'shawn', 'sheldon', 'silas', 'simon',
    'skyler', 'solomon', 'sonny', 'spencer', 'stanley', 'stefan', 'stephan', 'stephen', 'sterling',
    'steve', 'steven', 'stewart', 'stone', 'stuart', 'sullivan',
    'tanner', 'taylor', 'ted', 'terry', 'thaddeus', 'theodore', 'thomas', 'timothy', 'titus', 'tobias',
    'toby', 'todd', 'tom', 'tommy', 'tony', 'trace', 'travis', 'trent', 'trenton', 'trevor', 'trey',
    'tristan', 'troy', 'tucker', 'ty', 'tyler', 'tyson',
    'ulysses', 'uriel',
    'valentino', 'vance', 'vaughn', 'vernon', 'vicente', 'victor', 'vincent', 'virgil',
    'wade', 'walker', 'wallace', 'walt', 'walter', 'ward', 'warren', 'wayne', 'wendell', 'wesley',
    'weston', 'will', 'william', 'willie', 'wilson', 'winston', 'wyatt',
    'xander', 'xavier',
    'yahir', 'yosef', 'yusuf',
    'zachary', 'zack', 'zane', 'zion'
]);

const FEMALE_NAMES = new Set([
    'aaliyah', 'abby', 'abigail', 'ada', 'addie', 'addison', 'adelaide', 'adele', 'adeline', 'adriana',
    'adrienne', 'agatha', 'agnes', 'aileen', 'aimee', 'ainsley', 'alaina', 'alana', 'alejandra', 'alexa',
    'alexandra', 'alexis', 'alice', 'alicia', 'alina', 'alison', 'allison', 'alma', 'alyssa', 'amanda',
    'amber', 'amelia', 'amy', 'ana', 'anastasia', 'andrea', 'angela', 'angelica', 'angelina', 'angie',
    'anita', 'ann', 'anna', 'annabel', 'annabelle', 'anne', 'annette', 'annie', 'april', 'arabella',
    'ariana', 'arianna', 'ariel', 'arlene', 'ashley', 'aspen', 'astrid', 'athena', 'aubrey', 'audrey',
    'aurora', 'autumn', 'ava', 'avery',
    'bailey', 'barbara', 'beatrice', 'becky', 'belinda', 'bella', 'bernadette', 'bernice', 'bertha',
    'bessie', 'beth', 'bethany', 'betty', 'beverly', 'bianca', 'billie', 'blair', 'blanche', 'bonnie',
    'brandi', 'brandy', 'breanna', 'brenda', 'brenna', 'briana', 'brianna', 'bridget', 'brittany',
    'brittney', 'brooke', 'brooklyn', 'brynn',
    'caitlin', 'caitlyn', 'callie', 'camila', 'camille', 'candace', 'candice', 'cara', 'carina', 'carla',
    'carly', 'carmen', 'carol', 'carolina', 'caroline', 'carolyn', 'carrie', 'casey', 'cassandra',
    'cassidy', 'cassie', 'catalina', 'catherine', 'cecilia', 'celeste', 'celia', 'chandra', 'charlene',
    'charlotte', 'chelsea', 'cheri', 'cheryl', 'chloe', 'christa', 'christina', 'christine', 'cindy',
    'claire', 'clara', 'clarissa', 'claudia', 'colleen', 'constance', 'cora', 'corinne', 'courtney',
    'crystal', 'cynthia',
    'dahlia', 'daisy', 'dakota', 'dana', 'daniela', 'danielle', 'daphne', 'darla', 'darlene', 'dawn',
    'deanna', 'debbie', 'deborah', 'debra', 'deirdre', 'delia', 'delilah', 'denise', 'desiree', 'destiny',
    'diana', 'diane', 'dianne', 'dina', 'dolores', 'donna', 'dora', 'doreen', 'doris', 'dorothy',
    'dulce',
    'eden', 'edith', 'eileen', 'elaine', 'eleanor', 'elena', 'eliana', 'elisa', 'elizabeth', 'ella',
    'ellen', 'eloise', 'elsa', 'elsie', 'elvira', 'emery', 'emilia', 'emily', 'emma', 'emmeline',
    'enid', 'erica', 'erika', 'erin', 'esmeralda', 'esperanza', 'estelle', 'esther', 'ethel', 'eulalia',
    'eva', 'evangeline', 'eve', 'evelyn', 'evie',
    'faith', 'fanny', 'farrah', 'fatima', 'faye', 'felicia', 'fern', 'fiona', 'flora', 'florence',
    'frances', 'francesca', 'francine', 'frankie', 'franziska', 'freda', 'freya', 'frieda',
    'gabriela', 'gabriella', 'gabrielle', 'gail', 'gemma', 'genevieve', 'georgia', 'geraldine',
    'gertrude', 'gia', 'gigi', 'gillian', 'gina', 'giselle', 'gladys', 'glenda', 'gloria', 'grace',
    'gracie', 'gretchen', 'gwendolyn',
    'hadley', 'hailey', 'haley', 'hannah', 'harley', 'harmony', 'harper', 'harriet', 'hattie', 'hayley',
    'hazel', 'heather', 'heidi', 'helen', 'helena', 'helaine', 'henrietta', 'hilary', 'hillary', 'holly',
    'hope',
    'ida', 'imani', 'imogen', 'ina', 'ines', 'ingrid', 'irene', 'iris', 'irma', 'isabel', 'isabella',
    'isabelle', 'isla', 'ivana', 'ivy',
    'jackie', 'jacqueline', 'jade', 'jamie', 'jan', 'jana', 'jane', 'janelle', 'janet', 'janice',
    'janine', 'jannie', 'jasmine', 'jayne', 'jean', 'jeanette', 'jeanne', 'jeannie', 'jen', 'jena',
    'jenn', 'jenna', 'jenni', 'jennie', 'jennifer', 'jenny', 'jeri', 'jess', 'jessica', 'jessie',
    'jewel', 'jill', 'jillian', 'joan', 'joanna', 'jocelyn', 'jodi', 'jodie', 'jody', 'joelle',
    'johanna', 'jolene', 'jolie', 'jordan', 'josephine', 'josie', 'joy', 'joyce', 'juanita', 'judith',
    'judy', 'julia', 'juliana', 'julianne', 'julie', 'juliet', 'juliette', 'june', 'justine',
    'kaitlin', 'kaitlyn', 'kali', 'kamila', 'kara', 'karen', 'karina', 'karla', 'karyn', 'kate',
    'katelyn', 'katerina', 'katherine', 'kathleen', 'kathryn', 'kathy', 'katie', 'katrina', 'kay',
    'kaya', 'kayla', 'kaylee', 'keara', 'keisha', 'keli', 'kelli', 'kelly', 'kelsey', 'kendra',
    'kennedy', 'kerry', 'kim', 'kimberly', 'kira', 'kiran', 'kirsten', 'kristen', 'kristie', 'kristin',
    'kristina', 'kristine', 'krystal', 'kyla', 'kylie', 'kyra',
    'lacey', 'laila', 'lana', 'lara', 'larissa', 'laura', 'laurel', 'lauren', 'laverne', 'layla',
    'lea', 'leah', 'leigh', 'lena', 'leona', 'leslie', 'lesley', 'leticia', 'libby', 'lila', 'lillian',
    'lillie', 'lilly', 'lily', 'linda', 'lindsay', 'lindsey', 'lisa', 'liv', 'livia', 'liz', 'liza',
    'lizzie', 'lois', 'lola', 'lorena', 'loretta', 'lori', 'lorraine', 'lottie', 'louisa', 'louise',
    'lucia', 'lucille', 'lucinda', 'lucy', 'luisa', 'luna', 'lydia', 'lynn', 'lynne',
    'mabel', 'mackenzie', 'macy', 'madeleine', 'madeline', 'madelyn', 'maddie', 'madison', 'mae',
    'maggie', 'maisie', 'mallory', 'mandi', 'mandy', 'mara', 'marcella', 'marci', 'marcia', 'margaret',
    'margarita', 'marge', 'margot', 'maria', 'mariah', 'marian', 'marianne', 'marie', 'marilyn',
    'marina', 'marion', 'marissa', 'marjorie', 'marla', 'marlene', 'marley', 'marsha', 'marta',
    'martha', 'mary', 'matilda', 'maureen', 'maxine', 'maya', 'meagan', 'megan', 'meghan', 'melanie',
    'melinda', 'melissa', 'melody', 'mercedes', 'meredith', 'mia', 'michaela', 'michele', 'michelle',
    'mikayla', 'mildred', 'millie', 'mimi', 'mindy', 'minerva', 'miranda', 'miriam', 'missy', 'misty',
    'molly', 'mona', 'monet', 'monica', 'monique', 'morgan', 'muriel', 'mya', 'myla', 'myra', 'myrna',
    'myrtle',
    'nadia', 'nadine', 'nadya', 'nancy', 'naomi', 'natalia', 'natalie', 'natasha', 'nathalie', 'nellie',
    'neva', 'nicki', 'nicole', 'nikita', 'nikki', 'nina', 'noel', 'noelle', 'nola', 'nora', 'norah',
    'norma', 'nydia',
    'octavia', 'olga', 'olive', 'olivia', 'opal', 'ophelia',
    'paige', 'pam', 'pamela', 'paola', 'pat', 'patience', 'patricia', 'patsy', 'patty', 'paula',
    'paulette', 'paulina', 'pauline', 'pearl', 'peggy', 'penelope', 'penny', 'petra', 'peyton', 'phoebe',
    'phyllis', 'piper', 'polly', 'poppy', 'portia', 'priscilla',
    'queen',
    'rachael', 'rachel', 'ramona', 'randi', 'raquel', 'raven', 'rayana', 'reagan', 'rebecca', 'reese',
    'regan', 'regina', 'rena', 'renata', 'rene', 'renee', 'rhea', 'rhonda', 'riley', 'rita', 'roberta',
    'robin', 'rochelle', 'rosa', 'rosalie', 'rosalind', 'rosalyn', 'rose', 'rosemary', 'rosie',
    'roxanne', 'ruby', 'ruth', 'rylee',
    'sabrina', 'sadie', 'sally', 'samantha', 'sandra', 'sandy', 'sara', 'sarah', 'sasha', 'savannah',
    'scarlett', 'selena', 'selma', 'serena', 'shannon', 'shari', 'sharianne', 'sharon', 'shayla',
    'shayna', 'sheila', 'shelby', 'shelley', 'sheri', 'sherri', 'sherry', 'sheryl', 'shirley', 'sierra',
    'sigrid', 'simone', 'sonya', 'sophia', 'sophie', 'stacey', 'stacie', 'stacy', 'stella', 'stephanie',
    'sue', 'summer', 'susan', 'susanne', 'susie', 'suzanne', 'suzi', 'suzette', 'sybil', 'sydney',
    'sylvia',
    'tabitha', 'talia', 'tamara', 'tammy', 'tania', 'tanya', 'tara', 'taryn', 'tasha', 'tatiana',
    'taylor', 'teanna', 'teresa', 'terri', 'terrie', 'terry', 'tessa', 'thea', 'thelma', 'theresa',
    'tiffany', 'tina', 'toni', 'tonya', 'tori', 'tracey', 'traci', 'tracie', 'tracy', 'tricia',
    'trina', 'trisha', 'trudy', 'trysha',
    'ursula',
    'valentina', 'valerie', 'vanessa', 'vera', 'veronica', 'vicki', 'vicky', 'victoria', 'viola',
    'violet', 'virginia', 'vivian', 'viviana', 'vivienne',
    'wanda', 'wendy', 'whitney', 'willa', 'willow', 'wilma', 'winifred', 'winnie',
    'ximena', 'xochitl',
    'yolanda', 'yvette', 'yvonne',
    'zara', 'zelda', 'zoe', 'zoey', 'zora'
]);

export function detectGenderFromName(displayName: string): { gender: 'male' | 'female'; probability: number } | null {
    if (!displayName) return null;

    // Extract first name
    const firstName = displayName.split(' ')[0].trim().toLowerCase();
    if (!firstName || firstName.length < 2) return null;

    if (MALE_NAMES.has(firstName)) {
        return { gender: 'male', probability: 0.92 };
    }

    if (FEMALE_NAMES.has(firstName)) {
        return { gender: 'female', probability: 0.92 };
    }

    // Try common nickname patterns
    const nicknames: Record<string, 'male' | 'female'> = {
        'bob': 'male', 'rob': 'male', 'mike': 'male', 'dave': 'male',
        'joe': 'male', 'tom': 'male', 'jim': 'male', 'tim': 'male',
        'ben': 'male', 'dan': 'male', 'sam': 'male', 'ted': 'male',
        'liz': 'female', 'sue': 'female', 'meg': 'female', 'jen': 'female',
        'kate': 'female', 'beth': 'female', 'ann': 'female', 'pat': 'female',
        'pam': 'female', 'deb': 'female', 'kim': 'female', 'val': 'female',
    };

    if (nicknames[firstName]) {
        return { gender: nicknames[firstName], probability: 0.88 };
    }

    return null;
}
